# Generated by Django 3.1.3 on 2021-07-26 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learnapp', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.user')),
                ('category', models.ManyToManyField(blank=True, to='learnapp.Category')),
                ('favourites', models.ManyToManyField(blank=True, to='learnapp.Post')),
            ],
        ),
    ]
