# Generated by Django 3.1.3 on 2021-08-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnapp', '0008_auto_20210804_1618'),
        ('accounts', '0003_auto_20210803_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='learnapp.Category'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='saved_posts',
            field=models.ManyToManyField(blank=True, null=True, to='learnapp.Post'),
        ),
    ]
