# Generated by Django 3.1.3 on 2021-08-04 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnapp', '0009_auto_20210804_2307'),
        ('accounts', '0004_auto_20210804_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='category',
            field=models.ManyToManyField(blank=True, to='learnapp.Category'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='saved_posts',
            field=models.ManyToManyField(blank=True, to='learnapp.Post'),
        ),
    ]
