# Generated by Django 3.1.3 on 2021-08-09 10:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210805_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=254, unique=True, validators=[django.core.validators.RegexValidator(code='Enter a valid username.', message='Only alphanumeric characters are allowed.', regex='^[a-zA-Z0-9]+$')]),
        ),
    ]
