# Generated by Django 3.1.3 on 2021-08-01 19:15

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnapp', '0002_auto_20210729_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(code='Enter a valid value', message='Tags can have only alphanumeric, hyphens and dashes', regex='^[\\w\\-\\s]+$')]), blank=True, null=True, size=10),
        ),
        migrations.AlterField(
            model_name='postsgroup',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(code='Enter a valid value', message='Tags can have only alphanumeric, hyphens and dashes', regex='^[\\w\\-\\s]+$')]), size=10),
        ),
    ]
