# Generated by Django 3.1.3 on 2021-08-03 10:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learnapp', '0004_auto_20210803_1554'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostsGroup',
            new_name='Collection',
        ),
    ]
