# Generated by Django 3.1.3 on 2021-08-03 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnapp', '0005_auto_20210803_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='posts',
            field=models.ManyToManyField(blank=True, null=True, to='learnapp.Post'),
        ),
    ]
