# Generated by Django 3.1.3 on 2021-08-09 10:07

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnapp', '0010_auto_20210805_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(code='Enter a valid tag.', message='Only lowercase alphanumeric, dash, space and hyphens are allowed.', regex='^[a-z0-9\\-_\\s]+$')]), blank=True, null=True, size=10),
        ),
    ]
