# Generated by Django 3.1.3 on 2021-09-11 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learnapp', '0012_auto_20210911_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='flagged',
        ),
    ]
