# Generated by Django 3.1.3 on 2021-10-13 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnapp', '0017_auto_20210923_0322'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon_url',
            field=models.URLField(default='https://firebasestorage.googleapis.com/v0/b/eager-app-dc4ed.appspot.com/o/icons%2Feagle.svg?alt=media&token=03759a99-7a07-428c-9b00-ecb86c7d0e6e'),
        ),
    ]
