# Generated by Django 3.1.3 on 2021-10-13 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learnapp', '0018_category_icon_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='icon_url',
        ),
    ]
